### ISSUE TITLE
sensitivity to CAMB parameters for high-z and/or low mass halos

### ISSUE THREAD

**Issue by mirochaj** [steven-murray/HMFcalc#6]
hmf results seem to be sensitive to some CAMB parameters, e.g., k_per_logint and kmax, whose defaults may not be suited to high redshifts and low halo masses. 

I've included a short script that shows the issue, made using hmf version 3.0.3 and camb version 0.1.7. Also, if "p.set_matter_power" is called without arguments (or even its default arguments), the results change, implying that a default MassFunction instance is perhaps not equivalent to a MassFunction instance created with a default CAMBparams object?

Note that this should be recoverable with earlier versions of hmf that used pycamb, though be aware that the relevant parameters have since changed names (from transfer__k_per_logint and transfer__kmax), and were previously passed into MassFunction via transfer_params as a simple dictionary rather than a CAMBparams instance.

Here's the test script:

    import camb
    from hmf import MassFunction
    from matplotlib import gridspec

    gs = gridspec.GridSpec(2, 1, height_ratios=[2, 1])
    ax0 = pl.subplot(gs[0])
    ax1 = pl.subplot(gs[1])

    p = camb.CAMBparams()
    p.set_matter_power(kmax=100)   # sensitive to k_per_logint as well

    # These are the defaults
    #p.set_matter_power([0.0], kmax=1.2, k_per_logint=None, nonlinear=None,
    #    accurate_massive_neutrino_transfers=False, silent=False)

    mf1 = MassFunction(Mmin=6)
    mf2 = MassFunction(Mmin=6, transfer_params={"camb_params":p})

    colors = ['k', 'b', 'g', 'm']
    for i, z in enumerate([0, 3, 6, 10]):
        mf1.update(z=z)
        mf2.update(z=z)
    
        ax0.loglog(mf1.m, mf1.ngtm, color=colors[i], ls='-', label=r'$z={}$'.format(z))
        ax0.loglog(mf2.m, mf2.ngtm, color=colors[i], ls='--', lw=3)
    
        ax1.semilogx(mf1.m, mf2.ngtm / mf1.ngtm, color=colors[i])

    ax0.legend(loc='lower left', fontsize=12)
    ax0.set_ylim(1e-12, 1e5)
    ax0.set_ylabel('ngtm')
    ax1.set_ylabel('new/default')
    ax1.set_xlabel('mass')
    ax0.set_xticklabels([])

**Comment by steven-murray** [comment]
Thanks for the report. For reference, the figure produced looks like this:

![derp](https://user-images.githubusercontent.com/1272030/40705007-4edf05a8-641c-11e8-9171-535936439f4b.png)

While I would prefer to stay with the defaults that CAMB specifies, do you think it would be useful to have dynamic defaults based on the redshift? Or should that be up to the user?

**Comment by mirochaj** [comment]
The least invasive solution I can think of is to add warnings to the MassFunction constructor and the 'update' method of that class that are triggered if the user supplies masses below ~10^11 or redshifts greater than z~ a few. Re-setting the defaults automatically will require a more detailed study of the most conservative values one needs for the CAMB parameters, which I suspect will be difficult to optimize and hard to implement, e.g., would we need a lookup table for optimal CAMB parameters as a function of M and z?

**Comment by steven-murray** [comment]
I agree with that. Do you mind doing a PR for this? Otherwise I'll get to it eventually :-)

**Comment by mirochaj** [comment]
Sorry for the delay, I issued a very simple PR via hmf. Hopefully it's useful?
